name: Deploy to Amazon ECS

on:
  push:
    branches: [ "DEMO3" ]

env:
  AWS_REGION: AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token : ${{secrets.aws_session_token}}
        aws-region: ${{ secrets.AWS_REGION }}

   # Step 3: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6 

    # Step 4: Terraform Init
    - name: Initialize Terraform
      run: terraform init
      working-directory: ./Terraform

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./Terraform

    # Step 6: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./Terraform
